newapp/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views
#from storekeeper import newapp

app_name = 'newapp'
urlpatterns = [
    url(r'^$', views.user_login, name='login'),
    url(r'^logout/', views.user_logout, name='logout'),
    url(r'^list/$', views.list, name='list'),
    url(r'^about/', views.about, name='about'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^register/$', views.register, name='register'),
    path('update/<str:pk>', views.updatelist, name='update'),
    path('delete/<str:pk>', views.deletelist, name='delete')
]

storekeeper/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from newapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'',include('newapp.urls')),

]

newapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Order(models.Model):
    item=models.CharField(max_length=200)
    quantity=models.CharField(max_length=200)
    date_ordered= models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.item

class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    message = models.CharField(max_length=500)

    def __str__(self):
        return self.name

class UserProfileInfo(models.Model):
    user =models.OneToOneField(User,on_delete=models.CASCADE) #on delete argument required since djnago 2.x

    #extra attributes

    StoreName = models.CharField(max_length=300)

    profile_pic =models.ImageField(upload_to='profile_pic',blank=True) #if the user uploads any profile pic, it gets saved to this section.

    def __str__(self):
        return self.user.username

newapp/forms.py
from django import forms
from .models import Order,Contact,UserProfileInfo
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields= ('username','email','password')
        widgets={
            'password': forms.TextInput(attrs={'placeholder':'Enter your Password'})
        }

class UserProfileInfoForm(forms.ModelForm):

    class Meta:
        model= UserProfileInfo
        fields = ('profile_pic','StoreName')

class OrderForm(forms.ModelForm):

    class Meta():
        model=Order
        fields= '__all__'

        widgets={
            'item': forms.TextInput(attrs={'placeholder':'Enter the item Name'}),
            'quantity': forms.TextInput(attrs={'placeholder':'Enter the Quantity'})
        }

class ContactForm(forms.ModelForm):
    
    class Meta():
        model=Contact
        fields= '__all__'

        widgets={
            'name': forms.TextInput(attrs={'placeholder':'Enter your name'}),
            'email': forms.TextInput(attrs={'placeholder':'Enter you email'}),
            'message':forms.TextInput(attrs={'placeholder':'Enter you message to be sent'})
        }

newapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.


def register(request):

    registered = False

    if(request.method == 'POST'):
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        # store_name=profile_form['StoreName']

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            # One to one relationship indicator(Will research into it in some moments)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'newapp/register.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST['username']
        # gets the username and password from the form supplied
        password = request.POST['password']

        # authenticates the user in a single line of code, Hail Django!
        user = authenticate(request, username=username, password=password)
        print("user:", user)
        if user:
            if user.is_active:
                login(request, user)
                # if user has logged in successfully, he/she would be redirected to the index page
                return HttpResponseRedirect('list')
            else:
                return HttpResponse("User not active")
        else:
            print("Someone tried to login who was not registered")
            print("username: {}, password: {}".format(username, password))
            return HttpResponse("Invalid Login details Supplied")
            # if a user who was not registered tries to login, then this happens
    else:
        return render(request, 'newapp/index.html', {})


@login_required  # a decorator which ensures this fn gets executed iff the user has logged in
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')


@login_required
def list(request):
    orders = Order.objects.all()
    form = OrderForm()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('newapp:list')

    context = {'order': orders, 'form': form}

    return render(request, 'newapp/list.html', context)


@login_required
def updatelist(request, pk):
    demand = Order.objects.get(id=pk)
    form = OrderForm(instance=demand)

    if request.method == 'POST':
        form = OrderForm(request.POST, instance=demand)
        if request.POST.get('submit') == 'Update':
            if form.is_valid():
                form.save()
                return redirect('newapp:list')
        elif request.POST.get('submit') == 'Cancel':
            if form.is_valid():
                return redirect('newapp:list')
    context = {'form': form}
    return render(request, 'newapp/update.html', context)


@login_required
def deletelist(request, pk):
    task = Order.objects.get(id=pk)
    #form= OrderForm()

    if request.method == 'POST':
        if request.POST.get('submit') == 'Yes,Delete':
            task.delete()
            return redirect('newapp:list')
        else:
            return redirect('newapp:list')
    context = {'task': task}
    return render(request, 'newapp/delete.html', context)


def contact(request):
    form1 = ContactForm()

    if request.method == 'POST':
        form1 = ContactForm(request.POST)

        if form1.is_valid():
            form1.save()
            return redirect('/')
    return render(request, 'newapp/contact.html', context={'form1': form1})


def about(request):
    return render(request, 'newapp/about.html')

templates/newapp/about.html
{% extends 'newapp/update.html' %}
{% load static %}

{% block body_block %}
<div class="all">
<div class="jumbotron">
{% block titleblock %}
<div class="title" style="margin-top:-10px;margin-left:-10px;font-size:1.5rem">
   <b>About Us</b>
</div>
<div class="about" style="width:90%;font-size:1.2rem;display:flex;align-items:center;justify-content:center;margin-left:20px">
<ul> <li><b>StoreKeeper</b> is a <b>CRUD</b> based web app for managing all the <b>stocks</b> for your store.</li><li> This web app has features like<b> Creating an order, Updating an Order, Marking an order as complete</b> and<b> deleting the order </b>as well.</li><li> Just log in here and forget all the long registers that you used for managing your orders. <b>Happy Managing !</b></li>
</ul>
</div>
</div>
</div>
{% endblock %}
{%endblock%}

templates/newapp/auxil.html
<div class="all">
<div class="jumbotron" style="margin-top:20%">
{% block titleblock %}
<div class="title" style="margin-top:-10px;margin-left:-10px;font-size:1.5rem">
   <b>Contact Us </b>
</div>
<form action="" method="POST">
   {% csrf_token %}
   {{form1}}
   <input type="submit" value="Send Message" class="btn btn-success" style="margin-top:5px">
</form>
<div class="title" style="margin-left:-10px;font-size:1.5rem">
   <b>Contribute on GitHub</b><br>
   <a href="https://github.com/shm-318/StoreKeeper.git" target="_blank"><i class="fab fa-github fa-2x" style="color:black"></i></a>
</div>
</div>
</div>

templates/newapp/contact.html
{% extends 'newapp/update.html' %} {% load static %} {% block css %}
<link href="{% static 'css/contact.css' %}" rel="stylesheet" type="text/css" />
{% endblock %} {% block body_block %}
<div class="all">
  <div class="jumbotron">
    {% block titleblock %}
    <div
      class="title"
      style="margin-top: -10px; margin-left: -10px; font-size: 1.5rem"
    >
      <b>Contact Us </b>
    </div>
    <form action="" method="POST">
      {% csrf_token %} {{form1}}
      <input
        type="submit"
        value="Send Message"
        class="btn btn-success"
        style="margin-top: 5px"
      />
    </form>
    <div class="title" style="margin-left: -10px; font-size: 1.5rem">
      <b>Contribute on GitHub</b><br />
      <a href="https://github.com/shm-318/StoreKeeper.git" target="_blank"
        ><i class="fab fa-github fa-2x" style="color: black"></i
      ></a>
    </div>
  </div>
</div>
{% endblock %} {%endblock%}

templates/newapp/delete.html
{% extends 'newapp/update.html' %}
{% load static %}

{% block body_block %}
<div class="all">
<div class="jumbotron">
{% block titleblock %}
<div class="title">
<span>
  Are you sure you want to <b>Delete</b> this item??,
  This action is <b>irreversible</b>
</span>
</div>
{% endblock %}
  <form action="" method="post">
      {% csrf_token %}
      <div class="buttons">
      <input type="submit" value="Yes,Delete" class="btn btn-success" name="submit">
      <input type="submit" value= "No,Cancel" class="btn btn-danger" name="submit">
    </div>
  </form>
</div>
</div>
{% endblock %}

templates/newapp/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>StoreKeeper</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    {% block css %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    {% endblock %}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />

    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Bree+Serif&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <div class="all">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">StoreKeeper</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'newapp:about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'newapp:contact' %}">Contact</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'newapp:logout' %}">Logout</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
      {% block body_block %}
      <div class="jumbotron">
        <form method="POST" action="" class="form">
          <p>Welcome to StoreKeeper!</p>
          <p>Login Here</p>
          {% csrf_token %}
          <label for="username">Username</label>
          <input type="text" name="username" placeholder="Enter Username" />

          <label for="password">Password</label>
          <input
            type="password"
            name="password"
            placeholder="Enter your password"
          />

          <input type="submit" value="Login" class="btn btn-success" />
          <h3 style="color: rgb(5, 5, 85); text-align: center">
            Not Registered Yet?
          </h3>
          <div class="container" style="margin-left: 0">
            <button type="button" class="btn btn-success">
              <a href="{% url 'newapp:register' %}">Register</a>
            </button>
          </div>
        </form>
      </div>
    </div>
    {% endblock %}
    <div class="footer">All rights reserved &nbsp;&nbsp;StoreKeeper Inc©</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="{%static 'js/index.js' %}"></script>
  </body>
</html>

templates/newapp/list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StoreKeeper</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    {% block css %}<link rel="stylesheet" href="{% static 'css/mystyle.css' %}">{% endblock %}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">  
   <link rel="preconnect" href="https://fonts.gstatic.com">
   <link href="https://fonts.googleapis.com/css2?family=Bree+Serif&display=swap" rel="stylesheet">
   
   
</head>
<body>
<div class="all">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">StoreKeeper</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'newapp:about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'newapp:contact' %}">Contact</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'newapp:logout' %}">Logout</a>
        </li>
        {% endif %}

      </ul>
    </div>
  </div>
</nav>
 {% block body_block%}
  <div class="container top">
    <p><b>StoreKeeper- Your own Store Manager</b></p>
  </div>
 
  <div class="jumbotron">
    <form action="" method="post">
        {% csrf_token %}
        {{form.item}}
        {{form.quantity}}
        <input type="submit" value="submit" class="btn btn-success">
    </form>
  </div>
  <div class="list" id="list1">
    {% for x in order %}
    <div class="container1">
    <span class="update" id="update1"> <a href="{% url 'newapp:update' x.id %}"><i class="fas fa-edit fa-2x"></i></a></span><span class="content" id="content1"> <b>Item</b>:&nbsp;{{x.item}} &nbsp;&nbsp; <b>Quantity:</b>&nbsp;{{x.quantity}}</span>
    <span class="delete" id="delete1">  <a href="{% url 'newapp:delete' x.id %}"><i class="fas fa-trash-alt fa-2x"></i></a></span> <span class="complete" id="complete1")><a href="#"> <i class="far fa-check-circle fa-2x"></i></a></span>
  </div>
    {% endfor %}
  </div>
  {%endblock%}
  <div class="footer">
    All rights reserved &nbsp;&nbsp;StoreKeeper Inc©
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src ="{%static 'js/index.js' %}"></script>
</body>
</html>

templates/newapp/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StoreKeeper</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    {% block css %}<link rel="stylesheet" href="{% static 'css/register.css' %}">{% endblock %}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">  
   <link rel="preconnect" href="https://fonts.gstatic.com">
   <link href="https://fonts.googleapis.com/css2?family=Bree+Serif&display=swap" rel="stylesheet">
   
   
</head>
<body>
<div class="all">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">StoreKeeper</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'newapp:about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'newapp:contact' %}">Contact</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'newapp:logout' %}">Logout</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
 </nav>
{% block body_block %}
<div class="jumbotron">
       {% if registered %}
          <h2 style="text-align: center; color:rgb(40, 40, 121)">Thankyou for registering</h2>
       {% else %}
          <h2 style="text-align: center; color:rgb(18, 18, 117)">Registration For StoreKeeper</h2>
          <form enctype="multipart/form-data" method="POST" class="form">
              {% csrf_token %}
              {{user_form.as_p}}
              {{profile_form.as_p}}
           <input type="submit" value="Register"class="btn btn-success">
          </form> 
       {% endif %}
   </div>
</div>
{% endblock %} 
  <div class="footer">
    All rights reserved &nbsp;&nbsp;StoreKeeper Inc©
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  
  <script src ="{%static 'js/index.js' %}"></script>
</body>
</html>

templates/newapp/update.html
{% extends 'newapp/list.html' %}
{% load static %}
{% block css %}
  <link href="{% static 'css/update.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% block body_block %}
<div class="all">
<div class="jumbotron">
{% block titleblock %}
<div class="title">
   Update Form
</div>
{% endblock %}
{% block contentblock %}
  <form action="" method="post">
      {% csrf_token %}
      {{form}}
    <div class="buttons">
      <input type="submit" value="Update" class="btn btn-success" name="submit">
      <input type="submit" value="Cancel" class="btn btn-danger" name="submit">
    </div>
  </form>
{% endblock %}
</div>
</div>
{% endblock %}